import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import reactRefreshPlugin from 'eslint-plugin-react-refresh';

export default [
  { ignores: ['dist'] },
  {
    files: ['**/*.{js,ts,jsx,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      globals: {
        node: 'readonly',
        browser: 'readonly',
      },
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      'react-refresh': reactRefreshPlugin,
    },
    rules: {
      'indent': ['error', 2],
      'semi': ['error', 'always'],
      'quotes': ['error', 'single'],
      'comma-dangle': ['error', 'always-multiline'],
      'space-before-function-paren': ['error', 'always'],
      'object-curly-spacing': ['error', 'always'],
      'padded-blocks': ['error', 'never'],
      'max-len': ['error', 80],
      'prefer-const': 'warn',
      'prefer-template': 'error',
      'consistent-return': 'error',
      'no-param-reassign': ['error', { props: false }],
      'no-else-return': 'error',
      'prefer-destructuring': ['error', { object: true, array: false }],
      'no-var': 'error',
      'no-unused-vars': 'warn',
      'no-shadow': 'error',
      'no-console': 'off',
      'no-restricted-syntax': ['error', 'WithStatement'],
      // 'no-alert': 'warn',
      // 'no-magic-numbers': ['warn', { ignoreArrayIndexes: true }],
      'no-new': 'off',
      'no-underscore-dangle': 'off',
      // 'camelcase': 'error',
      'linebreak-style': ['error', 'unix'],
      'eol-last': ['error', 'always'],
      'no-trailing-spaces': 'error',
      'object-curly-newline': ['error', { consistent: true }],
      'function-paren-newline': ['error', 'consistent'],
      'arrow-parens': ['error', 'always'],
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react': 'off',
      'react/jsx-uses-vars': 'error',
      'react/jsx-pascal-case': 'error',
      'react/jsx-indent': ['error', 2],
      'react/jsx-equals-spacing': ['error', 'never'],
      // 'react/jsx-no-bind': 'warn',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
];
